### ISSUE TITLE
We have both v2 and v3 definition files

### ISSUE THREAD

**Issue by Floppy** [carbon-intensity/api-definitions#2]
Currently we have `carbon-intensity.yaml` which is a swagger v2 file, and `carbon-intensity.yml` which is openapi v3 (basically the next version of swagger). I did the v3 one last week, but it looks like you've been creating an updated v2 one and generating docs from that. Which should we use? Probably makes sense just to have one :)

@g33kcentric @alasdairrwbruce @LyndonRuff

**Comment by alasdairrwbruce** [comment]
Hi James, I agree we should probably use v3 but not sure how to update/edit the yml file. Is there an online editor that we can use? Does it work with Slate?

**Comment by Floppy** [comment]
Yes, I've been using the interactive editor at http://editor.swagger.io/. I can do the change from 2-3, as I learned all the gotchas converting the last one, and have done a lot of the required work for that already. Will try to get it done later today.

I'm not sure about Slate - it will depend on the conversion tool I think. @g33kcentric, what did you use? Do you have a moment to try it on the existing v3 file, see if it works?

**Comment by g33kcentric** [comment]
Sorry for the delay, the attached file is the docs for the v3 yml
[build.zip](https://github.com/carbon-intensity/api-definitions/files/1318297/build.zip)

I used a tool called [widdershins](https://github.com/Mermade/widdershins) to convert the **yml** to **md**, then slate to turn that **md** to html.

**Comment by Floppy** [comment]
Great, thanks - looks like v3 will work fine. I'll get it updated.

**Comment by alasdairrwbruce** [comment]
James, v3 looks really great. But we are not sure how to convert it to html?

**Comment by Floppy** [comment]
I'm doing that at the moment, using widdershins and shins as @g33kcentric did. Unfortunately the definitions aren't quite coming through right, so something's up. It's not a showstopper though, as the existing docs that are online are completely correct, just not generated off the current v3 file.
